base_color: bg-nulltrace
paginator_pages: '10'
archive_dropdown: 'false'
tagsLimit: 20
darkmode: light
post:
  thumbnail: true
  noimage: true
  thumbnail_height: h-44
  thumbnail_width: w-auto
  description: '130'
widgets:
  display: true
  widgets:
    - search
    - archive
    - category
    - tags
    - recent
sharing: true
addthis_token: ra-613a62d4b8f1bc89
og_image: https://storage.googleapis.com/nulltrace-static/images/nulltrace_logo_red.png